[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:CCLJ/arch.nvim.git"
    refreshPeriod = "168h"
