# BEGIN_KITTY_FONTS
font_family      family="Iosevka"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# send shift+enter instead of a plain newline
# this is a fix when doing shift+enter inside claude while using tmux
# will use a solution on tmux conf and leave this commented out in case that doesn work
# map shift+enter send_text all \x1b[13;2u
