general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 600                            # in seconds. 5min
    on-timeout = loginctl lock-session       # command to run when timeout has passed.
}

listener {
    timeout = 700                          # 11min
    on-timeout = hyprctl dispatch dpms off # turn screen/monitor off, not suspend
    on-resume = hyprctl dispatch dpms on   # turn screen/monitor on
}

listener {
    timeout = 900                        # 15min
    on-timeout = systemctl suspend       # suspend pc
}
